
// C:\repository\proj-full-stack-backend\src\services\table\seed\grpservicos.seed.ts
type GrpservicosSeedType = {
  id: number;
  nome: string;
  id_servicos?: number;
  createdBy?: number;
  updatedBy?: number;
};
export const grpservicosSeed: GrpservicosSeedType[] = [
  // serviços : Designs
  { id: 1, nome: 'Desenvolvimento Gráfico', id_servicos: 1, createdBy: 0, updatedBy: 0 },
  { id: 2, nome: 'Design Bordado', id_servicos: 1, createdBy: 0, updatedBy: 0 },
  { id: 3, nome: 'Design DTF', id_servicos: 1, createdBy: 0, updatedBy: 0 },
  { id: 4, nome: 'Design Adesivo UV', id_servicos: 1, createdBy: 0, updatedBy: 0 },
  { id: 5, nome: 'Design Corte/Laser', id_servicos: 1, createdBy: 0, updatedBy: 0 },
  { id: 6, nome: 'Design Corte/Laser em MDF', id_servicos: 1, createdBy: 0, updatedBy: 0 },
  { id: 7, nome: 'Design Corte/Laser e Gravação em MDF', id_servicos: 1, createdBy: 0, updatedBy: 0 },
  { id: 8, nome: 'Design Gravação em Vidros', id_servicos: 1, createdBy: 0, updatedBy: 0 },
  { id: 9, nome: 'Design Gravação em Metal Chapinhas', id_servicos: 1, createdBy: 0, updatedBy: 0 },
  { id: 10, nome: 'Design Gravação em Metal Copos/Canécas', id_servicos: 1, createdBy: 0, updatedBy: 0 },
  { id: 11, nome: 'Design Gravação em MDF', id_servicos: 1, createdBy: 0, updatedBy: 0 },
  { id: 12, nome: 'Design Silkscreen', id_servicos: 1, createdBy: 0, updatedBy: 0 },
  // serviços : "Bordados"
  { id: 13, nome: 'Bordado Tecido', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 14, nome: 'Bordado Tecido e Corte Laser', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 15, nome: 'Bordado c/ Apliq. e Corte Laser', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 16, nome: 'Bordado Tecido "NOMES"', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 17, nome: 'Bordado Tecido "NOMES" c/ Apliq. Velcon', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 18, nome: 'Bordado Tecido c/ Apliq. Velcon', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 19, nome: 'Bordado Tecido c/ Apliq. Feltro Corte Laser ', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 20, nome: 'Bordado Tecido c/ Apliq. Lantejoula', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 21, nome: 'Bordado Tecido c/ Apliq. Lâ', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 22, nome: 'Bordado Tecido c/ Apliq. Cordão', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 23, nome: 'Bordado Tecido c/ Apliq. Rechilieur', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 24, nome: 'Bordado Tecido c/ Apliq. Soutache', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 25, nome: 'Bordado Tecido c/ relev. Negativo', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 26, nome: 'Bordado Tecido c/ relev. Positivo EVA', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 27, nome: 'Bordado Tecido c/ relev. Positivo EVA e Corte Laser', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 28, nome: 'Bordado Tecido c/ relev. Negativo ', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 29, nome: 'Bordado Tecido Gola', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 30, nome: 'Bordado Tecido Gola Peça Fechada', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 31, nome: 'Bordado Tecido Punho', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 32, nome: 'Bordado Tecido Punho Peça Fechada', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 33, nome: 'Bordado Tecido Manga', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 34, nome: 'Bordado Tecido Manga Peça Fechada', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 35, nome: 'Bordado Tecido Bolso', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 36, nome: 'Bordado Tecido Bolso Peça Fechada', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 37, nome: 'Bordado Tecido Bolso/Manga Peça Fechada', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 38, nome: 'Bordado Tecido Bolso c/ Apliq. Velcon Peça Fechada', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 39, nome: 'Bordado Plástico', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 40, nome: 'Bordado Plástico c/ Apliq, Corte Laser', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 41, nome: 'Bordado Venil', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 42, nome: 'Bordado Venil c/ Apliq. Corte Laser', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 43, nome: 'Bordado Napa/Corvin, (parecidos)', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 44, nome: 'Bordado Napa/Corvin, (parecidos) c/ Apliq. Corte Laser', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 45, nome: 'Bordado Palhas Trançadas c/ Apliq. Corte Laser', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 46, nome: 'Bordado Couro', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 47, nome: 'Bordado Couro c/ Apliq. Corte Laser', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 48, nome: 'Bordado Boné Fechado', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 49, nome: 'Bordado Boné Fechado c/ Apliq. e Corte Laser', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 50, nome: 'Bordado Boné Fechado c/ Apliq. relevo Positivo EVA', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 51, nome: 'Bordado Boné Fechado c/ Apliq. relevo Positivo EVA e Corte Laser', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 52, nome: 'Bordado Boné Fechado c/ Apliq. relevo Negativo ', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 53, nome: 'Bordado Boné Fechado c/ Apliq. Velcron e Corte Laser ', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 54, nome: 'Bordado Chapéu', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 55, nome: 'Bordado Chapéu c/ Apliq. e Corte Laser', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 56, nome: 'Bordado Chapéu c/ Apliq. em relevo Negativo ', id_servicos: 2, createdBy: 0, updatedBy: 0 },
  { id: 57, nome: 'Bordado Chapéu c/ Apliq. relevo Positivo EVA ', id_servicos: 2, createdBy: 0,},
  { id: 58, nome: 'Bordado Chapéu c/ Apliq. relevo Positivo EVA e Corte Laser', id_servicos: 2, createdBy: 0,},
  // serviços : DTF (Termo colante)
  { id: 59, nome: 'DTF Avulso', id_servicos: 3, createdBy: 0, updatedBy: 0 },
  { id: 60, nome: 'DTF com Aplique de Bordados', id_servicos: 3, createdBy: 0, updatedBy: 0 },
  { id: 61, nome: 'DTF com Bordados sobre o mesmo', id_servicos: 3, createdBy: 0, updatedBy: 0 },
  { id: 62, nome: 'DTF com aplique de Costura', id_servicos: 3, createdBy: 0, updatedBy: 0 },
  // serviços : Adesivo UV 
  { id: 63, nome: 'Adesivo UV Alfa Numérico', id_servicos: 4, createdBy: 0, updatedBy: 0 },
  { id: 64, nome: 'Adesivo UV Banner', id_servicos: 4, createdBy: 0, updatedBy: 0 },
  { id: 65, nome: 'Adesivo UV Logo', id_servicos: 4, createdBy: 0, updatedBy: 0 },
  { id: 66, nome: 'Adesivo UV Criatividade', id_servicos: 4, createdBy: 0, updatedBy: 0 },
  { id: 67, nome: 'Adesivo UV Painel', id_servicos: 4, createdBy: 0, updatedBy: 0 },
  { id: 68, nome: 'Adesivo UV (Outros)', id_servicos: 4, createdBy: 0, updatedBy: 0 },
  // serviços : Corte a Laser
  { id: 69, nome: 'Corte Laser', id_servicos: 5, createdBy: 0, updatedBy: 0 },
  { id: 70, nome: 'Corte Laser em Tecido', id_servicos: 5, createdBy: 0, updatedBy: 0 },
  { id: 71, nome: 'Corte Laser em Vinil', id_servicos: 5, createdBy: 0, updatedBy: 0 },
  { id: 72, nome: 'Corte Laser em Acrílico', id_servicos: 5, createdBy: 0, updatedBy: 0 },
  { id: 73, nome: 'Corte Laser em PVC', id_servicos: 5, createdBy: 0, updatedBy: 0 },
  { id: 74, nome: 'Corte Laser em Plastico', id_servicos: 5, createdBy: 0, updatedBy: 0 },
  { id: 75, nome: 'Corte Laser em Napa/Corvin, (parecidos)', id_servicos: 5, createdBy: 0, updatedBy: 0 },
  { id: 76, nome: 'Corte Laser em MDF', id_servicos: 5, createdBy: 0, updatedBy: 0 },
  { id: 77, nome: 'Corte Laser em DTF', id_servicos: 5, createdBy: 0, updatedBy: 0 },
  { id: 78, nome: 'Corte Laser em Couro', id_servicos: 5, createdBy: 0, updatedBy: 0 },
  { id: 79, nome: 'Corte Laser em Papel Ondulado', id_servicos: 5, createdBy: 0, updatedBy: 0 },
  { id: 80, nome: 'Corte Laser em Papel Cartão', id_servicos: 5, createdBy: 0, updatedBy: 0 },
  // serviços : Corte Lase e Gravação
  { id: 81, nome: 'Corte Lase/Gravação', id_servicos: 6, createdBy: 0, updatedBy: 0 },
  { id: 82, nome: 'Corte Lase/Gravação em Vinil', id_servicos: 6, createdBy: 0, updatedBy: 0 },
  { id: 83, nome: 'Corte Lase/Gravação em Acrílico', id_servicos: 6, createdBy: 0, updatedBy: 0 },
  { id: 84, nome: 'Corte Laser/Gravação em PVC', id_servicos: 6, createdBy: 0, updatedBy: 0 },
  { id: 85, nome: 'Corte Laser/Gravação em Plastico', id_servicos: 6, createdBy: 0, updatedBy: 0 },
  { id: 86, nome: 'Corte Laser/Gravação em Napa/Corvin, (parecidos)', id_servicos: 6, createdBy: 0, updatedBy: 0 },
  { id: 87, nome: 'Corte Laser/Gravação em Couro', id_servicos: 6, createdBy: 0, updatedBy: 0 },
  { id: 88, nome: 'Corte Laser/Gravação em MDF', id_servicos: 6, createdBy: 0, updatedBy: 0 },
  { id: 89, nome: 'Corte Laser/Gravação em DTF', id_servicos: 6, createdBy: 0, updatedBy: 0 },
  { id: 90, nome: 'Corte Laser/Gravação em Papel Ondulado', id_servicos: 6, createdBy: 0, updatedBy: 0 },
  { id: 91, nome: 'Corte Laser/Gravação em Papel Cartão', id_servicos: 6, createdBy: 0, updatedBy: 0 },
  // serviços : Gravação
  { id: 92, nome: 'Gravação', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 93, nome: 'Gravação em Vidro', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 94, nome: 'Gravação em Madeira', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 95, nome: 'Gravação em Metal', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 96, nome: 'Gravação em Vinil', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 97, nome: 'Gravação em Acrílico', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 98, nome: 'Gravação em PVC', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 99, nome: 'Gravação em Plastico', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 100, nome: 'Gravação em Napa/Corvin, (parecidos)', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 101, nome: 'Gravação em Couro', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 102, nome: 'Gravação em MDF', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 103, nome: 'Gravação em DTF', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 104, nome: 'Gravação em Papel Ondulado', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  { id: 105, nome: 'Gravação em Papel Cartão', id_servicos: 7, createdBy: 0, updatedBy: 0 },
  // serviços : Silkscreen
  { id: 106, nome: 'Silkscreen Tecido c/ 01 Côr', id_servicos: 8, createdBy: 0, updatedBy: 0 },
  { id: 107, nome: 'Silkscreen Tecido c/ 02 Côr', id_servicos: 8, createdBy: 0, updatedBy: 0 },
  { id: 108, nome: 'Silkscreen Tecido c/ 03 Côr', id_servicos: 8, createdBy: 0, updatedBy: 0 },
  { id: 109, nome: 'Silkscreen Tecido c/ 04 Côr', id_servicos: 8, createdBy: 0, updatedBy: 0 },
  { id: 110, nome: 'Silkscreen Tecido c/ 05 Côr', id_servicos: 8, createdBy: 0, updatedBy: 0 },
  { id: 111, nome: 'Silkscreen Tecido c/ 06 Côr', id_servicos: 8, createdBy: 0, updatedBy: 0 }
];
