
// C:\repository\proj-full-stack-backend\src\services\table\seed\perguntas.seed.ts
export const perguntasSeed = [
  { nome: 'De que maneira você vê o "mundo" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual a sua "religião" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "nome" você mais gosta ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "praia" você ja visitou ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "país" você ja visitou ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual a "cidade" que você nasceu ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual é a sua "idade" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual a sua "profissão" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "cor" você prefere ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "marca" de veículo você prefere ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "passeio" você prefere ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "sorvete" você prefere ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "pizza" você prefere ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "lanche" você prefere ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "bebida" você prefere ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "comida" você prefere ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "música" você prefere ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual parte do "dia" você prefere ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual "esporte" você prefere ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Qual a raça de "animal" você gosta ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Voce tem : "Casa" , "Apart." ou mora de "Aluguél" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você se sente : "Magro", "Nornmal" ou "Gordo" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você se sente Jovem : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você se tem filhos : "Sim"/"Não"/"não sabe" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você pratica esporte : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você sabe dirigir veiculos : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você tem hábito de dormir cêdo : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você acredita que irá ter dias melhore : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você já se sentiu traido por um amigo : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você já andou de bicicleta : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você já andou de motocicleta : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você já fêz passeios ou viagens de avião : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você já fêz passeios em trilhas na mata : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você já fêz passeios em trilhas de bicicleta : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você já fêz passeios de caronas : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você já fêz passeios noturnos : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você faz ginásticas, exercícios de alguma maneira : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você se acha uma pessoa "inteligente" : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você se acha uma pessoa "curiosa" : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
  { nome: 'Você se acha uma pessoa "simpática" : "Sim"/"Não" ?', createdBy: 0, updatedBy: 0 },
];

